# Generated by Django 5.0.7 on 2024-07-11 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TripsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='planner.tripsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LinksModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='planner.tripsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('occurs_at', models.DateTimeField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.tripsmodel')),
            ],
        ),
    ]
