# Generated by Django 5.0.7 on 2024-07-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitiesmodels',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='linksmodel',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.RenameField(
            model_name='participantsmodel',
            old_name='trip_id',
            new_name='trip',
        ),
    ]
